import typing


class Module(typing.NamedTuple):

    class BasicObjectConfig(typing.Protocol):
        def id_non_null_arg(self, src, info, *args): ...
        def string_non_null_arg(self, src, info, *args): ...
        def int_non_null_arg(self, src, info, *args): ...
        def float_non_null_arg(self, src, info, *args): ...
        def boolean_non_null_arg(self, src, info, *args): ...
        def id_arg(self, src, info, *args): ...
        def string_arg(self, src, info, *args): ...
        def int_arg(self, src, info, *args): ...
        def float_arg(self, src, info, *args): ...
        def boolean_arg(self, src, info, *args): ...

    BasicObject: BasicObjectConfig
