"""
  BasicObject description
"""
type BasicObject {
  idNonNull: ID!
  stringNonNull: String!
  intNonNull: Int!
  floatNonNull: Float!
  booleanNonNull: Boolean!
  """
    id description
  """
  id: ID
  """
    string description
  """
  string: String
  """
    int description
  """
  int: Int
  """
    float description
  """
  float: Float
  """
    boolean description
  """
  boolean: Boolean
  idNonNullArg("""
    idNonNull description
  """ idNonNull: ID! = "default"): ID!
  stringNonNullArg(stringNonNull: String! = "default"): String!
  intNonNullArg(intNonNull: Int! = 1): Int!
  floatNonNullArg(floatNonNull: Float! = 1): Float!
  booleanNonNullArg(booleanNonNull: Boolean! = true): Boolean!
  idArg(id: ID): ID
  stringArg(string: String): String
  intArg(int: Int): Int
  floatArg(float: Float): Float
  booleanArg(boolean: Boolean): Boolean
  basicScalar: BasicScalar
  basicInputArg(basicInput: BasicInput): String
  basicInputArgWithDefault(basicInput: BasicInput = {basicScalar: "123", boolean: true, float: 1, id: "default", int: 1, string: "default"}): String
  """
    extendedField description
  """
  extendedField: ID!
  extendedFieldWithArg(idNonNull: ID!): ID!
}

interface BasicInterface implements AnotherInterface {
  interfaceField: String
  basicScalar: BasicScalar
  extendedField: ID!
  extendedFieldWithArg(idNonNull: ID!): ID!
  anotherField: ID!
}

type BasicInterfaceImpl implements BasicInterface & AnotherInterface {
  interfaceField: String
  basicScalar: BasicScalar
  """
    extendedField description
  """
  extendedField: ID!
  extendedFieldWithArg(idNonNull: ID!): ID!
  anotherField: ID!
}

union BasicUnion = BasicObject | BasicInterfaceImpl | AnotherType

enum BasicEnum {
  """
    ENUM_VALUE_1 description
  """ ENUM_VALUE_1
  ENUM_VALUE_2
  """
    EXTENDED_VALUE description
  """ EXTENDED_VALUE
}

input BasicInput {
  """
    idNonNull description
  """ idNonNull: ID! = "default"
  stringNonNull: String! = "default"
  intNonNull: Int! = 1
  floatNonNull: Float! = 1
  booleanNonNull: Boolean! = true
  basicScalarNotNull: BasicScalar! = "123"
  id: ID
  string: String
  int: Int
  float: Float
  boolean: Boolean
  basicScalar: BasicScalar
  """
    extendedField description
  """ extendedField: ID!
}

"""
  BasicScalar description
"""
scalar BasicScalar

interface AnotherInterface {
  anotherField: ID!
}

type AnotherType {
  anotherField: ID!
}

type DeprecatedFieldObject {
  deprecatedField: String @deprecated(reason: "No longer supported")
}

type ModuleB {
  id: ID!
  name: String!
}

type ModuleA {
  id: ID!
  name: String!
}

type Nested2 {
  value: String
}

type Nested1 {
  nested2: Nested2
}

interface GrandParent {
  echo(message: String!): String!
  echoSync(message: String!): String!
}

interface Parent implements GrandParent {
  echo(message: String!): String!
  echoSync(message: String!): String!
}

type Child implements GrandParent & Parent {
  echo(message: String!): String!
  echoSync(message: String!): String!
  basicInterface: BasicInterface
  basicInterfaceList: [BasicInterface]
  basicInterfaceNonNullList: [BasicInterface]!
  basicInterfaceNonNullListNonNullElement: [BasicInterface!]!
  basicUnion: BasicUnion
  basicUnionList: [BasicUnion]
  basicUnionNonNullList: [BasicUnion]!
  basicUnionNonNullListNonNullElement: [BasicUnion!]!
  basicEnum: BasicEnum
  basicEnumList: [BasicEnum]
  basicEnumNonNullList: [BasicEnum]!
  basicEnumNonNullListNonNullElement: [BasicEnum!]!
}

type GraphQLObject {
  foo: String!
}

type graphql {
  bar: String!
}

type typing {
  baz: String!
}

type Query {
  version: String
  extendedHello(name: String!): String!
}

type Mutation {
  version: String
}

scalar DateTime

type Source {
  a: Int
}
