type BasicObject {
  idNonNull: ID!
  stringNonNull: String!
  intNonNull: Int!
  floatNonNull: Float!
  booleanNonNull: Boolean!
  id: ID
  string: String
  int: Int
  float: Float
  boolean: Boolean
  idNonNullArg(idNonNull: ID! = "default"): ID!
  stringNonNullArg(stringNonNull: String! = "default"): String!
  intNonNullArg(intNonNull: Int! = 1): Int!
  floatNonNullArg(floatNonNull: Float! = 1): Float!
  booleanNonNullArg(booleanNonNull: Boolean! = true): Boolean!
  idArg(id: ID): ID
  stringArg(string: String): String
  intArg(int: Int): Int
  floatArg(float: Float): Float
  booleanArg(boolean: Boolean): Boolean
  basicScalar: BasicScalar
  extendedField: ID!
  extendedFieldWithArg(idNonNull: ID!): ID!
}

interface BasicInterface implements AnotherInterface {
  interfaceField: String
  basicScalar: BasicScalar
  extendedField: ID!
  extendedFieldWithArg(idNonNull: ID!): ID!
  anotherField: ID!
}

type BasicInterfaceImpl implements BasicInterface & AnotherInterface {
  interfaceField: String
  basicScalar: BasicScalar
  extendedField: ID!
  extendedFieldWithArg(idNonNull: ID!): ID!
  anotherField: ID!
}

union BasicUnion = BasicObject | BasicInterfaceImpl | AnotherType

enum BasicEnum {
  ENUM_VALUE_1
  ENUM_VALUE_2
  EXTENDED_VALUE
}

input BasicInput {
  idNonNull: ID! = "default"
  stringNonNull: String! = "default"
  intNonNull: Int! = 1
  floatNonNull: Float! = 1
  booleanNonNull: Boolean! = true
  basicScalarNotNull: BasicScalar! = "123"
  id: ID
  string: String
  int: Int
  float: Float
  boolean: Boolean
  basicScalar: BasicScalar
  extendedField: ID!
}

"""
  BasicScalar description
"""
scalar BasicScalar

interface AnotherInterface {
  anotherField: ID!
}

type AnotherType {
  anotherField: ID!
}

type DeprecatedFieldObject {
  deprecatedField: String @deprecated(reason: "No longer supported")
}

type Query {
  version: String
}

type Mutation {
  version: String
}
