sudo: required
language: node_js
node_js:
  - '10'
  - '9'
  - '8'
  - '6'
services:
  - docker

install:
  - npm run bootstrap

before_script:
  - docker-compose up -d

script:
  - npm run coverage
  - npm run coverage:upload
