extend type BasicObject {
    """extendedField description"""
    extendedField: ID!
    extendedFieldWithArg(idNonNull: ID!): ID!
}

interface AnotherInterface {
    anotherField: ID!
}

extend interface BasicInterface implements AnotherInterface {
    extendedField: ID!
    extendedFieldWithArg(idNonNull: ID!): ID!
    anotherField: ID!
}

extend type BasicInterfaceImpl implements AnotherInterface {
    """extendedField description"""
    extendedField: ID!
    extendedFieldWithArg(idNonNull: ID!): ID!
    anotherField: ID!
}

type AnotherType {
    anotherField: ID!
}

extend union BasicUnion = AnotherType

extend enum BasicEnum {
    """EXTENDED_VALUE description"""
    EXTENDED_VALUE
}

extend input BasicInput {
    """extendedField description"""
    extendedField: ID!
}

extend type Query {
    extendedHello(name: String!): String!
}
