# GENERATED. DO NOT EDIT.
# fmt: off
import typing

from . import source


class BuilderConfig:
    class Basic(typing.NamedTuple):
        class Schema(typing.NamedTuple):
            class BasicObjectResolver(typing.Protocol):
                def idNonNull(self, obj: "source.BasicObjectSource", info, **args): ...
                def stringNonNull(self, obj: "source.BasicObjectSource", info, **args): ...
                def intNonNull(self, obj: "source.BasicObjectSource", info, **args): ...
                def floatNonNull(self, obj: "source.BasicObjectSource", info, **args): ...
                def booleanNonNull(self, obj: "source.BasicObjectSource", info, **args): ...
                def id(self, obj: "source.BasicObjectSource", info, **args): ...
                def string(self, obj: "source.BasicObjectSource", info, **args): ...
                def int(self, obj: "source.BasicObjectSource", info, **args): ...
                def float(self, obj: "source.BasicObjectSource", info, **args): ...
                def boolean(self, obj: "source.BasicObjectSource", info, **args): ...
                def idNonNullArg(self, obj: "source.BasicObjectSource", info, **args): ...
                def stringNonNullArg(self, obj: "source.BasicObjectSource", info, **args): ...
                def intNonNullArg(self, obj: "source.BasicObjectSource", info, **args): ...
                def floatNonNullArg(self, obj: "source.BasicObjectSource", info, **args): ...
                def booleanNonNullArg(self, obj: "source.BasicObjectSource", info, **args): ...
                def idArg(self, obj: "source.BasicObjectSource", info, **args): ...
                def stringArg(self, obj: "source.BasicObjectSource", info, **args): ...
                def intArg(self, obj: "source.BasicObjectSource", info, **args): ...
                def floatArg(self, obj: "source.BasicObjectSource", info, **args): ...
                def booleanArg(self, obj: "source.BasicObjectSource", info, **args): ...
                def basicScalar(self, obj: "source.BasicObjectSource", info, **args): ...
            class BasicInterfaceResolver(typing.Protocol):
                def interfaceField(self, obj: "source.BasicInterfaceSource", info, **args): ...
                def basicScalar(self, obj: "source.BasicInterfaceSource", info, **args): ...
            class BasicInterfaceImplResolver(typing.Protocol):
                def interfaceField(self, obj: "source.BasicInterfaceImplSource", info, **args): ...
                def basicScalar(self, obj: "source.BasicInterfaceImplSource", info, **args): ...
        _Schema: Schema
    class root(typing.NamedTuple):
        class QueryResolver(typing.Protocol):
            def version(self, obj: "source.QuerySource", info, **args): ...
        class MutationResolver(typing.Protocol):
            def version(self, obj: "source.MutationSource", info, **args): ...
    _Basic: Basic
    _root: root
