# GENERATED. DO NOT EDIT.
# fmt: off
from . import source_spec
import graphql
import typing


class Basic:
    class Definition:
        class BasicObject(typing.Protocol):
            async def id_non_null_arg(self, obj: source_spec.BasicObject, info: graphql.GraphQLResolveInfo, id_non_null: object) -> object: ...
            async def string_non_null_arg(self, obj: source_spec.BasicObject, info: graphql.GraphQLResolveInfo, string_non_null: str) -> str: ...
            async def int_non_null_arg(self, obj: source_spec.BasicObject, info: graphql.GraphQLResolveInfo, int_non_null: int) -> int: ...
            async def float_non_null_arg(self, obj: source_spec.BasicObject, info: graphql.GraphQLResolveInfo, float_non_null: float) -> float: ...
            async def boolean_non_null_arg(self, obj: source_spec.BasicObject, info: graphql.GraphQLResolveInfo, boolean_non_null: bool) -> bool: ...
            async def id_arg(self, obj: source_spec.BasicObject, info: graphql.GraphQLResolveInfo, id: object | None) -> object | None: ...
            async def string_arg(self, obj: source_spec.BasicObject, info: graphql.GraphQLResolveInfo, string: str | None) -> str | None: ...
            async def int_arg(self, obj: source_spec.BasicObject, info: graphql.GraphQLResolveInfo, int_: int | None) -> int | None: ...
            async def float_arg(self, obj: source_spec.BasicObject, info: graphql.GraphQLResolveInfo, float_: float | None) -> float | None: ...
            async def boolean_arg(self, obj: source_spec.BasicObject, info: graphql.GraphQLResolveInfo, boolean: bool | None) -> bool | None: ...
            async def basic_input_arg(self, obj: source_spec.BasicObject, info: graphql.GraphQLResolveInfo, basic_input: source_spec.BasicInput | None) -> str | None: ...
            async def basic_input_arg_with_default(self, obj: source_spec.BasicObject, info: graphql.GraphQLResolveInfo, basic_input: source_spec.BasicInput | None) -> str | None: ...

        class BasicInterface(typing.Protocol):
            pass

        class BasicInterfaceImpl(typing.Protocol):
            pass

        class BasicScalar(typing.Protocol):
            def serialize(self, value: typing.Any) -> typing.Any: ...
            def parse_value(self, value: typing.Any) -> typing.Any: ...
            def parse_literal(self, node: graphql.ValueNode, variables: typing.Any) -> typing.Any: ...

    class Extension:
        class BasicObject(typing.Protocol):
            async def extended_field_with_arg(self, obj: source_spec.BasicObject, info: graphql.GraphQLResolveInfo, id_non_null: object) -> object: ...

        class AnotherInterface(typing.Protocol):
            pass

        class BasicInterface(typing.Protocol):
            async def extended_field_with_arg(self, obj: source_spec.BasicInterface, info: graphql.GraphQLResolveInfo, id_non_null: object) -> object: ...

        class BasicInterfaceImpl(typing.Protocol):
            async def extended_field_with_arg(self, obj: source_spec.BasicInterfaceImpl, info: graphql.GraphQLResolveInfo, id_non_null: object) -> object: ...

        class AnotherType(typing.Protocol):
            pass

        class Query(typing.Protocol):
            async def extended_hello(self, obj: source_spec.Query, info: graphql.GraphQLResolveInfo, name: str) -> str: ...

class Deprecation:
    class Definition:
        class DeprecatedFieldObject(typing.Protocol):
            pass

class Module:
    class Module:
        class module:
            class ModuleB(typing.Protocol):
                pass

    class module:
        class ModuleA(typing.Protocol):
            pass

class Nested1:
    class Nested2:
        class nested2:
            class Nested2(typing.Protocol):
                pass

    class nested1:
        class Nested1(typing.Protocol):
            pass

class Resolve:
    class Schema:
        class GrandParent(typing.Protocol):
            async def echo(self, obj: source_spec.GrandParent, info: graphql.GraphQLResolveInfo, message: str) -> str: ...
            def echo_sync(self, obj: source_spec.GrandParent, info: graphql.GraphQLResolveInfo, message: str) -> str: ...

        class Parent(typing.Protocol):
            async def echo(self, obj: source_spec.Parent, info: graphql.GraphQLResolveInfo, message: str) -> str: ...
            async def echo_sync(self, obj: source_spec.Parent, info: graphql.GraphQLResolveInfo, message: str) -> str: ...

        class Child(typing.Protocol):
            async def echo(self, obj: source_spec.Child, info: graphql.GraphQLResolveInfo, message: str) -> str: ...
            async def echo_sync(self, obj: source_spec.Child, info: graphql.GraphQLResolveInfo, message: str) -> str: ...
            async def basic_interface(self, obj: source_spec.Child, info: graphql.GraphQLResolveInfo, ) -> source_spec.BasicInterface | None: ...
            async def basic_interface_list(self, obj: source_spec.Child, info: graphql.GraphQLResolveInfo, ) -> list[source_spec.BasicInterface | None] | None: ...
            async def basic_interface_non_null_list(self, obj: source_spec.Child, info: graphql.GraphQLResolveInfo, ) -> list[source_spec.BasicInterface | None]: ...
            async def basic_interface_non_null_list_non_null_element(self, obj: source_spec.Child, info: graphql.GraphQLResolveInfo, ) -> list[source_spec.BasicInterface]: ...
            async def basic_union(self, obj: source_spec.Child, info: graphql.GraphQLResolveInfo, ) -> source_spec.BasicUnion | None: ...
            async def basic_union_list(self, obj: source_spec.Child, info: graphql.GraphQLResolveInfo, ) -> list[source_spec.BasicUnion | None] | None: ...
            async def basic_union_non_null_list(self, obj: source_spec.Child, info: graphql.GraphQLResolveInfo, ) -> list[source_spec.BasicUnion | None]: ...
            async def basic_union_non_null_list_non_null_element(self, obj: source_spec.Child, info: graphql.GraphQLResolveInfo, ) -> list[source_spec.BasicUnion]: ...
            async def basic_enum(self, obj: source_spec.Child, info: graphql.GraphQLResolveInfo, ) -> source_spec.BasicEnum | None: ...
            async def basic_enum_list(self, obj: source_spec.Child, info: graphql.GraphQLResolveInfo, ) -> list[source_spec.BasicEnum | None] | None: ...
            async def basic_enum_non_null_list(self, obj: source_spec.Child, info: graphql.GraphQLResolveInfo, ) -> list[source_spec.BasicEnum | None]: ...
            async def basic_enum_non_null_list_non_null_element(self, obj: source_spec.Child, info: graphql.GraphQLResolveInfo, ) -> list[source_spec.BasicEnum]: ...

class graphql_:
    class GraphQLObject(typing.Protocol):
        pass

    class graphql_(typing.Protocol):
        pass

    class typing_(typing.Protocol):
        pass

class root:
    class Query(typing.Protocol):
        pass

    class Mutation(typing.Protocol):
        pass

class source:
    class source:
        class Source(typing.Protocol):
            async def a(self, obj: source_spec.Source, info: graphql.GraphQLResolveInfo, ) -> int | None: ...
