# GENERATED. DO NOT EDIT.
# fmt: off
from . import source_spec
import graphql
import typing


class Currency:
class IAM:
    class User:
        class User(typing.Protocol):
            def id(self, obj: source_spec.User, info: graphql.GraphQLResolveInfo, ) -> object: ...

        class UserID(typing.Protocol):
            def serialize(self, value: typing.Any) -> typing.Any: ...
            def parse_value(self, value: typing.Any) -> typing.Any: ...
            def parse_literal(self, node: graphql.ValueNode, variables: typing.Any) -> typing.Any: ...

        class UserConnection(typing.Protocol):
            pass

        class UserEdge(typing.Protocol):
            async def node(self, obj: source_spec.UserEdge, info: graphql.GraphQLResolveInfo, ) -> source_spec.User | None: ...

        class Query(typing.Protocol):
            async def user(self, obj: source_spec.Query, info: graphql.GraphQLResolveInfo, id: source_spec.UserID) -> source_spec.User: ...
            async def user_connection(self, obj: source_spec.Query, info: graphql.GraphQLResolveInfo, first: int | None, after: source_spec.Cursor | None, last: int | None, before: source_spec.Cursor | None, offset: int | None, filter: source_spec.UserFilter | None) -> source_spec.UserConnection: ...

    class Viewer:
        class Query(typing.Protocol):
            async def viewer(self, obj: source_spec.Query, info: graphql.GraphQLResolveInfo, ) -> source_spec.User | None: ...

class Orders:
    class Order:
        class Order(typing.Protocol):
            def id(self, obj: source_spec.Order, info: graphql.GraphQLResolveInfo, ) -> object: ...
            async def orderer(self, obj: source_spec.Order, info: graphql.GraphQLResolveInfo, ) -> source_spec.User: ...

        class OrderProduct(typing.Protocol):
            pass

        class OrderID(typing.Protocol):
            def serialize(self, value: typing.Any) -> typing.Any: ...
            def parse_value(self, value: typing.Any) -> typing.Any: ...
            def parse_literal(self, node: graphql.ValueNode, variables: typing.Any) -> typing.Any: ...

        class OrderConnection(typing.Protocol):
            pass

        class OrderEdge(typing.Protocol):
            async def node(self, obj: source_spec.OrderEdge, info: graphql.GraphQLResolveInfo, ) -> source_spec.Order | None: ...

        class Query(typing.Protocol):
            async def order(self, obj: source_spec.Query, info: graphql.GraphQLResolveInfo, id: source_spec.OrderID) -> source_spec.Order: ...
            async def order_connection(self, obj: source_spec.Query, info: graphql.GraphQLResolveInfo, first: int | None, after: source_spec.Cursor | None, last: int | None, before: source_spec.Cursor | None, offset: int | None, filter: source_spec.OrderFilter | None) -> source_spec.OrderConnection: ...

        class User(typing.Protocol):
            async def orders(self, obj: source_spec.User, info: graphql.GraphQLResolveInfo, first: int | None, after: source_spec.Cursor | None, last: int | None, before: source_spec.Cursor | None, offset: int | None, filter: source_spec.OrderFilter | None) -> source_spec.OrderConnection: ...

        class OrderCreateInDraftPayload(typing.Protocol):
            pass

        class Mutation(typing.Protocol):
            async def order_create_in_draft(self, obj: source_spec.Mutation, info: graphql.GraphQLResolveInfo, input: source_spec.OrderCreateInDraftInput) -> source_spec.OrderCreateInDraftPayload: ...

class Relay:
    class Node(typing.Protocol):
        pass

    class PageInfo(typing.Protocol):
        pass

    class Query(typing.Protocol):
        async def node(self, obj: source_spec.Query, info: graphql.GraphQLResolveInfo, id: object) -> source_spec.Node | None: ...
        async def nodes(self, obj: source_spec.Query, info: graphql.GraphQLResolveInfo, ids: list[object]) -> list[source_spec.Node | None]: ...

    class Cursor(typing.Protocol):
        def serialize(self, value: typing.Any) -> typing.Any: ...
        def parse_value(self, value: typing.Any) -> typing.Any: ...
        def parse_literal(self, node: graphql.ValueNode, variables: typing.Any) -> typing.Any: ...

class Root:
    class Query(typing.Protocol):
        def version(self, obj: source_spec.Query, info: graphql.GraphQLResolveInfo, ) -> str: ...

    class Mutation(typing.Protocol):
        pass

    class Timestamp(typing.Protocol):
        def serialize(self, value: typing.Any) -> typing.Any: ...
        def parse_value(self, value: typing.Any) -> typing.Any: ...
        def parse_literal(self, node: graphql.ValueNode, variables: typing.Any) -> typing.Any: ...

    class Decimal(typing.Protocol):
        def serialize(self, value: typing.Any) -> typing.Any: ...
        def parse_value(self, value: typing.Any) -> typing.Any: ...
        def parse_literal(self, node: graphql.ValueNode, variables: typing.Any) -> typing.Any: ...
