# GENERATED. DO NOT EDIT.
# fmt: off
from . import source_spec
import graphql
import typing


class Bookmark:
    class Bookmark:
        class Bookmark(typing.Protocol):
            async def bookmarker(self, obj: source_spec.BookmarkSource, info: graphql.GraphQLResolveInfo, ) -> source_spec.UserSource: ...
            async def bookmarkable(self, obj: source_spec.BookmarkSource, info: graphql.GraphQLResolveInfo, ) -> source_spec.BookmarkableSource: ...

        class BookmarkID(typing.Protocol):
            def serialize(self, value: typing.Any) -> typing.Any: ...
            def parse_value(self, value: typing.Any) -> typing.Any: ...
            def parse_literal(self, node: graphql.ValueNode, variables: typing.Any) -> typing.Any: ...

        class BookmarkConnection(typing.Protocol):
            pass

        class BookmarkEdge(typing.Protocol):
            async def node(self, obj: source_spec.BookmarkEdgeSource, info: graphql.GraphQLResolveInfo, ) -> source_spec.BookmarkSource | None: ...

    class Bookmarkable:
        class BookmarkableID(typing.Protocol):
            def serialize(self, value: typing.Any) -> typing.Any: ...
            def parse_value(self, value: typing.Any) -> typing.Any: ...
            def parse_literal(self, node: graphql.ValueNode, variables: typing.Any) -> typing.Any: ...

        class BookmarkableBookmarkPayload(typing.Protocol):
            async def bookmarkable_bookmarked(self, obj: source_spec.BookmarkableBookmarkPayloadSource, info: graphql.GraphQLResolveInfo, ) -> source_spec.BookmarkableSource: ...

        class BookmarkableUnbookmarkPayload(typing.Protocol):
            async def bookmarkable_unbookmarked(self, obj: source_spec.BookmarkableUnbookmarkPayloadSource, info: graphql.GraphQLResolveInfo, ) -> source_spec.BookmarkableSource: ...

        class Mutation(typing.Protocol):
            async def bookmark_bookmarkable(self, obj: source_spec.MutationSource, info: graphql.GraphQLResolveInfo, input: source_spec.BookmarkableBookmarkInputSource) -> source_spec.BookmarkableBookmarkPayloadSource | None: ...
            async def unbookmark_bookmarkable(self, obj: source_spec.MutationSource, info: graphql.GraphQLResolveInfo, input: source_spec.BookmarkableUnbookmarkInputSource) -> source_spec.BookmarkableUnbookmarkPayloadSource | None: ...

class Currency:
class IAM:
    class User:
        class User(typing.Protocol):
            def id(self, obj: source_spec.UserSource, info: graphql.GraphQLResolveInfo, ) -> object: ...

        class UserID(typing.Protocol):
            def serialize(self, value: typing.Any) -> typing.Any: ...
            def parse_value(self, value: typing.Any) -> typing.Any: ...
            def parse_literal(self, node: graphql.ValueNode, variables: typing.Any) -> typing.Any: ...

        class UserConnection(typing.Protocol):
            pass

        class UserEdge(typing.Protocol):
            async def node(self, obj: source_spec.UserEdgeSource, info: graphql.GraphQLResolveInfo, ) -> source_spec.UserSource | None: ...

        class Query(typing.Protocol):
            async def user(self, obj: source_spec.QuerySource, info: graphql.GraphQLResolveInfo, id: source_spec.UserIDSource) -> source_spec.UserSource: ...
            async def user_connection(self, obj: source_spec.QuerySource, info: graphql.GraphQLResolveInfo, first: int | None, after: source_spec.CursorSource | None, last: int | None, before: source_spec.CursorSource | None, offset: int | None, filter: source_spec.UserFilterSource | None) -> source_spec.UserConnectionSource: ...

    class Viewer:
        class Query(typing.Protocol):
            async def viewer(self, obj: source_spec.QuerySource, info: graphql.GraphQLResolveInfo, ) -> source_spec.UserSource | None: ...

class Orders:
    class Order:
        class Order(typing.Protocol):
            def id(self, obj: source_spec.OrderSource, info: graphql.GraphQLResolveInfo, ) -> object: ...
            async def orderer(self, obj: source_spec.OrderSource, info: graphql.GraphQLResolveInfo, ) -> source_spec.UserSource: ...
            async def viewer_has_bookmarked(self, obj: source_spec.OrderSource, info: graphql.GraphQLResolveInfo, ) -> bool: ...

        class OrderProduct(typing.Protocol):
            pass

        class OrderID(typing.Protocol):
            def serialize(self, value: typing.Any) -> typing.Any: ...
            def parse_value(self, value: typing.Any) -> typing.Any: ...
            def parse_literal(self, node: graphql.ValueNode, variables: typing.Any) -> typing.Any: ...

        class OrderConnection(typing.Protocol):
            pass

        class OrderEdge(typing.Protocol):
            async def node(self, obj: source_spec.OrderEdgeSource, info: graphql.GraphQLResolveInfo, ) -> source_spec.OrderSource | None: ...

        class Query(typing.Protocol):
            async def order(self, obj: source_spec.QuerySource, info: graphql.GraphQLResolveInfo, id: source_spec.OrderIDSource) -> source_spec.OrderSource: ...
            async def order_connection(self, obj: source_spec.QuerySource, info: graphql.GraphQLResolveInfo, first: int | None, after: source_spec.CursorSource | None, last: int | None, before: source_spec.CursorSource | None, offset: int | None, filters: list[source_spec.OrderFilterSource] | None) -> source_spec.OrderConnectionSource: ...

        class User(typing.Protocol):
            async def orders(self, obj: source_spec.UserSource, info: graphql.GraphQLResolveInfo, first: int | None, after: source_spec.CursorSource | None, last: int | None, before: source_spec.CursorSource | None, offset: int | None, filters: list[source_spec.OrderFilterSource] | None) -> source_spec.OrderConnectionSource: ...

        class OrderCreateInDraftPayload(typing.Protocol):
            pass

        class Mutation(typing.Protocol):
            async def order_create_in_draft(self, obj: source_spec.MutationSource, info: graphql.GraphQLResolveInfo, input: source_spec.OrderCreateInDraftInputSource) -> source_spec.OrderCreateInDraftPayloadSource | None: ...

class Relay:
    class PageInfo(typing.Protocol):
        pass

    class Query(typing.Protocol):
        async def node(self, obj: source_spec.QuerySource, info: graphql.GraphQLResolveInfo, id: object) -> source_spec.NodeSource | None: ...
        async def nodes(self, obj: source_spec.QuerySource, info: graphql.GraphQLResolveInfo, ids: list[object]) -> list[source_spec.NodeSource | None]: ...

    class Cursor(typing.Protocol):
        def serialize(self, value: typing.Any) -> typing.Any: ...
        def parse_value(self, value: typing.Any) -> typing.Any: ...
        def parse_literal(self, node: graphql.ValueNode, variables: typing.Any) -> typing.Any: ...

class Root:
    class Query(typing.Protocol):
        def version(self, obj: source_spec.QuerySource, info: graphql.GraphQLResolveInfo, ) -> str: ...

    class Mutation(typing.Protocol):
        pass

    class Timestamp(typing.Protocol):
        def serialize(self, value: typing.Any) -> typing.Any: ...
        def parse_value(self, value: typing.Any) -> typing.Any: ...
        def parse_literal(self, node: graphql.ValueNode, variables: typing.Any) -> typing.Any: ...

    class Decimal(typing.Protocol):
        def serialize(self, value: typing.Any) -> typing.Any: ...
        def parse_value(self, value: typing.Any) -> typing.Any: ...
        def parse_literal(self, node: graphql.ValueNode, variables: typing.Any) -> typing.Any: ...

    class TypeID(typing.Protocol):
        def serialize(self, value: typing.Any) -> typing.Any: ...
        def parse_value(self, value: typing.Any) -> typing.Any: ...
        def parse_literal(self, node: graphql.ValueNode, variables: typing.Any) -> typing.Any: ...
