# GENERATED. DO NOT EDIT.
# fmt: off
import typing

from ... import source


class Config(typing.NamedTuple):
    class BasicObjectConfig(typing.Protocol):
        def id_non_null_arg(self, obj: source.BasicObjectSource, info, **args): ...
        def string_non_null_arg(self, obj: source.BasicObjectSource, info, **args): ...
        def int_non_null_arg(self, obj: source.BasicObjectSource, info, **args): ...
        def float_non_null_arg(self, obj: source.BasicObjectSource, info, **args): ...
        def boolean_non_null_arg(self, obj: source.BasicObjectSource, info, **args): ...
        def id_arg(self, obj: source.BasicObjectSource, info, **args): ...
        def string_arg(self, obj: source.BasicObjectSource, info, **args): ...
        def int_arg(self, obj: source.BasicObjectSource, info, **args): ...
        def float_arg(self, obj: source.BasicObjectSource, info, **args): ...
        def boolean_arg(self, obj: source.BasicObjectSource, info, **args): ...
    
    class BasicInterfaceConfig(typing.Protocol):
        pass
    
    class BasicInterfaceImplConfig(typing.Protocol):
        pass
    
    BasicObject: BasicObjectConfig
    BasicInterface: BasicInterfaceConfig
    BasicInterfaceImpl: BasicInterfaceImplConfig
