interface GrandParent {
    echo(message: String!): String! @resolve
    echoSync(message: String!): String! @resolve(sync: true)
}

interface Parent implements GrandParent {
    echo(message: String!): String!
    echoSync(message: String!): String!
}

type Child implements GrandParent & Parent {
    echo(message: String!): String!
    echoSync(message: String!): String!

    basicInterface: BasicInterface @resolve
    basicInterfaceList: [BasicInterface] @resolve
    basicInterfaceNonNullList: [BasicInterface]! @resolve
    basicInterfaceNonNullListNonNullElement: [BasicInterface!]! @resolve

    basicUnion: BasicUnion @resolve
    basicUnionList: [BasicUnion] @resolve
    basicUnionNonNullList: [BasicUnion]! @resolve
    basicUnionNonNullListNonNullElement: [BasicUnion!]! @resolve

    basicEnum: BasicEnum @resolve
    basicEnumList: [BasicEnum] @resolve
    basicEnumNonNullList: [BasicEnum]! @resolve
    basicEnumNonNullListNonNullElement: [BasicEnum!]! @resolve
}